// components/layout/Layout.js

import Head from "next/head";
import React, { Fragment, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";
import Sidebar from "./Sidebar";

const Layout = ({ children, title = "Sample Title", isLoggedIn, onLogin }) => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleUsernameChange = (event) => {
    setUsername(event.target.value);
  };

  const handlePasswordChange = (event) => {
    setPassword(event.target.value);
  };

  const handleLoginClick = () => {
    // Perform login logic with username and password
    onLogin(username, password);
  };

  return (
    <Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoggedIn ? (
        <div className="flex bg-gray-100 min-h-screen relative">
          <Sidebar />
          <div className="flex-grow text-gray-800">
            <Header />
            {children}
          </div>
          <Footer />
        </div>
      ) : (
        <div className="flex items-center justify-center h-screen">
          <div className="border p-4">
            <h2>Login</h2>
            <label>
              Username:
              <input
                type="text"
                value={username}
                onChange={handleUsernameChange}
                className="border p-2 m-2"
              />
            </label>
            <br />
            <label>
              Password:
              <input
                type="password"
                value={password}
                onChange={handlePasswordChange}
                className="border p-2 m-2"
              />
            </label>
            <br />
            <button onClick={handleLoginClick} className="bg-blue-500 text-white p-2">
              Log In
            </button>
          </div>
        </div>
      )}
    </Fragment>
  );
};

export default Layout;
